export const LOCALSTORAGE_KEYS = {
  AUTH: "ODING_FORGE_AUTH_CONTEXT",
  STRIPE_SESSION_ID: "ODING_FORGE_STRIPE_SESSION_ID",
  AMPLITUDE_ANNONYMOUS_ID: "AMPLITUDE_ANNONYMOUS_ID",
  PAYMENT_LOADER: "ODING_FORGE_PAYMENT_LOADER",
};

export const COOKIE_KEYS = {
  JWT_TOKEN: "ODING_FORGE_AUTH_JWT_TOKEN",
};

export const URL_PARAMS_KEYS = {
  LOGIN_EMAIL_TOKEN: "ODING_FORGE_LOGIN_EMAIL_TOKEN",
};
